version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    env_file: .env        # подхватит POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5

  api:
    build:
      context: .          # путь к Dockerfile вашего микросервиса
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    env_file: .env        # подхватит DATABASE_URL
    ports:
      - "8000:8000"       # пробросит порт FastAPI наружу

volumes:
  db_data:                # том для хранения данных Postgres
